config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :flights
  root 'flights#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  scope :active, -> { where(status: 'Active')}
  scope :by_dest_origin, -> (from, to ) { where(origin: from, destination: to) }
  scope :by_departure_date, -> (dept_date) { where(departure_time: dept_date.beginning_of_day..dept_date.end_of_day)}

  has_many :bookings
  has_many :users, through: :bookings

  enum status: %w( Active Cancelled Delayed )

  def self.search search
    if search.present?
      active.by_dest_origin(search[:origin], search[:destination]).by_departure_date(Date.strptime(search[:dep_date], '%m/%d/%Y'))
    else
      active
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:create, :new]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.search(search_params)
  end

  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:name, :origin, :destination, :arrival_time, :departure_time)
    end

    def search_params
      params.permit(:origin, :destination, :dep_date, :return_date, :no_of_passengers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to 'My Flight', root_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      	<%= link_to 'Home', root_path, :class => 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav my-2 my-lg-0">
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
        	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
		  		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
        </div>
      </li>
    <% else %>
	    <li class="nav-item active">
	    	<%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
	    </li>
	    <li class="nav-item active">
	    	<%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
	    </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/application/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/flights/_flight.html.erb
<div class="card" style="width: 18rem;">
	<%= image_tag 'plane.png', class: 'card-img-top'%>
  <div class="card-body">
    <h5 class="card-title"><%= flight.name %></h5>
    <p class="card-text"><%= flight.origin  %> To <%= flight.destination  %></p>
    <p class="card-text"><%= flight.departure_time  %></p>
  </div>
</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :flight_name %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :flight_origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :flight_destination %>
  </div>

  <div class="field">
    <%= form.label :arrival_time %>
    <%= form.datetime_select :arrival_time, id: :flight_arrival_time %>
  </div>

  <div class="field">
    <%= form.label :departure_time %>
    <%= form.datetime_select :departure_time, id: :flight_departure_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_search_bar.html.erb
<%= link_to 'Add Flight', new_flight_path %>
<div class="flight-engine">
 <div class="container">
    <div class="tabing">
       <div class="tab-content">
        <%= form_tag flights_path, method: :get do |f| %>
          <div id="1" class="tab1 active">
             <div class="flight-tab row">
                <div class="persent-one">
                   <i class="fa fa-map-marker" aria-hidden="true"></i>
                   <%= text_field_tag :origin, params[:origin], placeholder: "From City or airport", class: "textboxstyle"%>
                </div>
                <div class="persent-one">
                   <i class="fa fa-map-marker" aria-hidden="true"></i>
                  <%= text_field_tag :destination, params[:destination], placeholder: "To City or airport", class: "textboxstyle"%>
                </div>
                <div class="persent-one less-per">
                   <i class="fa fa-calendar" aria-hidden="true"></i>
                   <%= text_field_tag :dep_date, params[:dep_date], data:{ provide: :datepicker }, placeholder: 'DD-MM-YYYY', class: "datepicker" %>
                   <%#= text_field_tag :dep_date, params[:dep_date], placeholder: "Departure Date", class: "textboxstyle"%>
                </div>
                <div class="persent-one less-per">
                   <i class="fa fa-calendar" aria-hidden="true"></i>
                   <%= text_field_tag :return_date, params[:return_date], data:{ provide: :datepicker }, placeholder: 'DD-MM-YYYY', class: "datepicker" %>
                   <%#= text_field_tag :return_date, params[:return_date], placeholder: "Return date", class: "textboxstyle"%>
                </div>
                <div class="persent-one">
                   <i class="fa fa-user" aria-hidden="true"></i>
                   <%= text_field_tag :no_of_passengers, params[:no_of_passengers], placeholder: "No of Passengers", class: "textboxstyle"%>
                </div>
                <div class="persent-one less-btn">
                  <%= submit_tag "search", class: 'cst-btn' %>
                </div>
             </div>
             <!-- flight tab -->
          </div>
        <% end %>
         <!-- tab 1 -->
       </div>
       </div>
       <!-- tab content -->
    </div>
    <!-- tabbing -->
 </div>
</div>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<%= render partial: 'search_bar' %>
<%= render @flights %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flight.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @flight.arrival_time %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @flight.departure_time %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airlineapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<body cz-shortcut-listen="true" class='bg-overlay'>
		<%= render partial: 'notice' %>
    <%= render partial: 'header' %>

		<main role="main" class="container">
		  <div class="starter-template">
		    <%= yield %>
		  </div>
		</main>
  </body>
</html>